database:
  dialect: duckdb
  credentials:
    database: .duck.db
    read_only: False
  schema: duck.metadata

ui:
  entities:
    - type: services
      name: сервисы
    - type: projects
      name: проекты
    - type: roles
      name: роли
    - type: users
      name: пользователи

server:
  host: 0.0.0.0
  title: Каталог доступов
  port: 80
